use_frameworks!

platform :ios, '9.0'

target 'NLSwiftSuger_Example' do
  pod 'NLSwiftSuger', :path => '../'

  target 'NLSwiftSuger_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
