use_frameworks!

platform :ios, '10.0'

target 'NLSwiftSuger_Example' do
  pod 'NLSwiftSuger', :path => '../'
  
  pod 'SnapKit'

  target 'NLSwiftSuger_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
